<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class CreatProjectRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|unique:projects',
            'thumbnail' => 'image|dimensions:min_width=261,min_height=98'
        ];
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required' => '项目名称必填！',
            'name.unique' => '项目名称已使用！',
            'thumbnail.image' => '请上传图片！',
            'thumbnail.dimensions' => '请上传261*98以上的图片！'
        ];
    }
}
