<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class editProjectRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|unique:projects',

        ];
    }
    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required' => '项目名称必填！',
            'name.unique' => '项目名称已使用！'
        ];
    }
}
